name: Build and run Flutter tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  setup:
    name: Build and run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/--

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.3

      - name: Build
        run: |
          cd flutter-frontend/perfect8_front_end
          flutter build

      - name: Run tests
        run: |
          cd flutter-frontend/perfect8_front_end
          flutter test
