name: Build and run Spring Boot tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  setup:
    name: Build and run Spring Boot tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24 # Keep this in sync with the java version in pom.xml

      - name: Build
        run: |
          cd spring-backend
          mvn --batch-mode clean install

      - name: Run tests
        run: |
          cd spring-backend
          mvn --batch-mode test
